"""add cases and cas_transitions tables

Revision ID: 064194354a66
Revises: 5f65a2e85060
Create Date: 2026-07-23 00:55:05.735879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '064194354a66'
down_revision: Union[str, Sequence[str], None] = '5f65a2e85060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ns_id', sa.String(), nullable=False),
    sa.Column('ns_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVING', 'RESOLVED', name='casestatus'), nullable=False),
    sa.Column('resolving_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ns_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ns_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stations_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('alternative', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_ns_id'), 'cases', ['ns_id'], unique=False)
    op.create_table('case_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_response_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_transitions')
    op.drop_index(op.f('ix_cases_ns_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
